name: Grammar Check for JSON Schema

on:
  pull_request:
  workflow_dispatch:

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Gramma
      run: npm install -g gramma

    - name: American-British-English-Translator
      run: npm install -g american-british-english-translator

    - name: Extract descriptions, property names, enums, and meta:enum
      run: |
        # Find all JSON schema files and extract relevant data
        find . -name "*.json" -print0 | while IFS= read -r -d '' file; do
          # Extract descriptions
          jq -r '..|.description? // empty' "$file" >> descriptions.txt
          # Extract property names
          jq -r 'paths(scalars) as $p | ($p[-1] | tostring) // empty' "$file" >> properties.txt
          # Extract enum values
          jq -r '..|.enum? // empty | .[]?' "$file" >> enums.txt
          # Extract meta:enum values
          jq -r '..|."meta:enum"? // empty | .[]?' "$file" >> meta_enum.txt
        done

    - name: Split and Check descriptions for grammar issues
      run: |
        split -l 50 descriptions.txt descriptions_chunk_
        for file in descriptions_chunk_*; do
          echo "Checking $file..."
          if ! gramma check -m -p "$file"; then
            echo "Grammar issues found in $file."
            exit 1
          fi
          sleep 10
        done

    - name: Split and Check property names for grammar issues
      run: |
        split -l 50 properties.txt properties_chunk_
        for file in properties_chunk_*; do
          echo "Checking $file..."
          if ! gramma check -m -p "$file"; then
            echo "Grammar issues found in $file."
            exit 1
          fi
          sleep 10
        done

    - name: Split and Check enum values for grammar issues
      run: |
        split -l 50 enums.txt enums_chunk_
        for file in enums_chunk_*; do
          echo "Checking $file..."
          if ! gramma check -m -p "$file"; then
            echo "Grammar issues found in $file."
            exit 1
          fi
          sleep 10
        done

    - name: Split and Check meta:enum values for grammar issues
      run: |
        split -l 50 meta_enum.txt meta_enum_chunk_
        for file in meta_enum_chunk_*; do
          echo "Checking $file..."
          if ! gramma check -m -p "$file"; then
            echo "Grammar issues found in $file."
            exit 1
          fi
          sleep 10
        done

    - name: Analyzing English Language (descriptions)
      run: english-translate descriptions.txt --spelling --no-color --firstonly 

    - name: Analyzing English Language (meta:enum)
      run: english-translate meta_enum.txt --spelling --no-color --firstonly 
