name: Grammar Check for JSON Schema

on:
  pull_request:
  workflow_dispatch:

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Gramma
      run: npm install -g gramma

    - name: Extract descriptions, property names, enums, and meta:enum
      run: |
        # Find all JSON schema files and extract relevant data
        find . -name "*.json" -print0 | while IFS= read -r -d '' file; do
          # Extract descriptions
          jq -r '..|.description? // empty' "$file" >> descriptions.txt
          # Extract property names
          jq -r 'paths(scalars) as $p | ($p[-1] | tostring) // empty' "$file" >> properties.txt
          # Extract enum values
          jq -r '..|.enum? // empty | .[]?' "$file" >> enums.txt
          # Extract meta:enum values
          jq -r '..|."meta:enum"? // empty | .[]?' "$file" >> meta_enum.txt
        done

    - name: Check descriptions for grammar issues
      run: |
        if [ -s descriptions.txt ]; then
          echo "Checking descriptions..."
          if ! gramma -m check descriptions.txt; then
            echo "Grammar issues found in descriptions."
            exit 1
          fi
        else
          echo "No descriptions found in JSON schema files."
        fi

    - name: Check property names for grammar issues
      run: |
        if [ -s properties.txt ]; then
          echo "Checking property names..."
          if ! gramma -m check properties.txt; then
            echo "Grammar issues found in property names."
            exit 1
          fi
        else
          echo "No property names found in JSON schema files."
        fi

    - name: Check enum values for grammar issues
      run: |
        if [ -s enums.txt ]; then
          echo "Checking enum values..."
          if ! gramma -m check enums.txt; then
            echo "Grammar issues found in enum values."
            exit 1
          fi
        else
          echo "No enum values found in JSON schema files."
        fi

    - name: Check meta:enum values for grammar issues
      run: |
        if [ -s meta_enum.txt ]; then
          echo "Checking meta:enum values..."
          if ! gramma -m check meta_enum.txt; then
            echo "Grammar issues found in meta:enum values."
            exit 1
          fi
        else
          echo "No meta:enum values found in JSON schema files."
        fi
